/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package blocodenotasmariacecilia;

import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import javax.swing.JFileChooser;

/**
 *
 * @author Aluno GTI
 */
public class GUI_BlocodeNotas extends javax.swing.JFrame {

    /**
     * Creates new form GUI_BlocodeNotas
     */
    public GUI_BlocodeNotas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btn_abrir = new javax.swing.JToggleButton();
        btn_Salvar = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtablocodenotas = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnabrir = new javax.swing.JMenuItem();
        btnsalvar = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btncopiar = new javax.swing.JMenuItem();
        btnRECORTAR = new javax.swing.JMenuItem();
        btnCOLAR = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btn_abrir.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btn_abrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blocodenotasmariacecilia/iconfinder_document-open_118911.png"))); // NOI18N
        btn_abrir.setFocusable(false);
        btn_abrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_abrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_abrirActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_abrir);

        btn_Salvar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btn_Salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blocodenotasmariacecilia/iconfinder_diskette_43574.png"))); // NOI18N
        btn_Salvar.setFocusable(false);
        btn_Salvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Salvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalvarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_Salvar);

        jtablocodenotas.setColumns(20);
        jtablocodenotas.setLineWrap(true);
        jtablocodenotas.setRows(5);
        jScrollPane1.setViewportView(jtablocodenotas);

        jMenu1.setText("Arquivo");

        btnabrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        btnabrir.setText("Abrir");
        btnabrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnabrirActionPerformed(evt);
            }
        });
        jMenu1.add(btnabrir);

        btnsalvar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        btnsalvar.setText("Salvar");
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });
        jMenu1.add(btnsalvar);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setText("Sair");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        btncopiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        btncopiar.setText("Copiar");
        btncopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncopiarActionPerformed(evt);
            }
        });
        jMenu2.add(btncopiar);

        btnRECORTAR.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        btnRECORTAR.setText("Recortar");
        btnRECORTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRECORTARActionPerformed(evt);
            }
        });
        jMenu2.add(btnRECORTAR);

        btnCOLAR.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        btnCOLAR.setText("Colar");
        btnCOLAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCOLARActionPerformed(evt);
            }
        });
        jMenu2.add(btnCOLAR);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ajuda");

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText("Sobre");
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnabrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnabrirActionPerformed
        this.abrir();
    }
    private void abrir() {
        int returnVal = fileChooser.showOpenDialog(this);
 if (returnVal == JFileChooser.APPROVE_OPTION) {
 File file = fileChooser.getSelectedFile();
 try {
 // What to do with the file, e.g. display it in a TextArea
 jtablocodenotas.read( new FileReader( file.getAbsolutePath() ), null );
 } catch (IOException ex) {
 System.out.println("problem accessing file"+file.getAbsolutePath());
 }
 } else {
 System.out.println("File access cancelled by user.");
 }
    }//GEN-LAST:event_btnabrirActionPerformed

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
      this.salvar();
    }
    private void salvar(){
        
    try { 
        File arquivo;
        JFileChooser arq = new JFileChooser();
        int Result = arq.showSaveDialog(this);
        if (Result == JFileChooser.APPROVE_OPTION) {
            arquivo = arq.getSelectedFile();
            FileWriter inArq = new FileWriter (arquivo.getPath());
            inArq.write(jtablocodenotas.getText());
            inArq.close();
        }
    } catch (IOException e ) {
        
    }
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void btn_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_abrirActionPerformed
     
 int returnVal = fileChooser.showOpenDialog(this);
 if (returnVal == JFileChooser.APPROVE_OPTION) {
 File file = fileChooser.getSelectedFile();
 try {
 // What to do with the file, e.g. display it in a TextArea
 jtablocodenotas.read( new FileReader( file.getAbsolutePath() ), null );
 } catch (IOException ex) {
 System.out.println("problem accessing file"+file.getAbsolutePath());
 }
 } else {
 System.out.println("File access cancelled by user.");
 }
    

        
    }//GEN-LAST:event_btn_abrirActionPerformed

    private void btn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalvarActionPerformed

    try { 
        File arquivo;
        JFileChooser arq = new JFileChooser();
        int Result = arq.showSaveDialog(this);
        if (Result == JFileChooser.APPROVE_OPTION) {
            arquivo = arq.getSelectedFile();
            FileWriter inArq = new FileWriter (arquivo.getPath());
            inArq.write(jtablocodenotas.getText());
            inArq.close();
        }
    } catch (IOException e ) {
        
    }
    }//GEN-LAST:event_btn_SalvarActionPerformed

    private void btncopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncopiarActionPerformed
         jtablocodenotas.copy();
        
    }//GEN-LAST:event_btncopiarActionPerformed

    private void btnCOLARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCOLARActionPerformed
        jtablocodenotas.paste();
        
    }//GEN-LAST:event_btnCOLARActionPerformed

    private void btnRECORTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRECORTARActionPerformed
        jtablocodenotas.cut();
    }//GEN-LAST:event_btnRECORTARActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.fechar();
    }
    private void fechar() {
        if(javax.swing.JOptionPane.showConfirmDialog
        (null, "Deseja Fechar?!", "ATENÇÃO!", javax.swing.JOptionPane.YES_NO_OPTION)==0){
            this.dispose();
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_BlocodeNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_BlocodeNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_BlocodeNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_BlocodeNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_BlocodeNotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnCOLAR;
    private javax.swing.JMenuItem btnRECORTAR;
    private javax.swing.JToggleButton btn_Salvar;
    private javax.swing.JToggleButton btn_abrir;
    private javax.swing.JMenuItem btnabrir;
    private javax.swing.JMenuItem btncopiar;
    private javax.swing.JMenuItem btnsalvar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextArea jtablocodenotas;
    // End of variables declaration//GEN-END:variables
JFileChooser fileChooser = new JFileChooser();

}
